/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* UART_DMA_INT */
#define UART_DMA_INT__INTC_CORTEXM4_ASSIGNED 1
#define UART_DMA_INT__INTC_CORTEXM4_PRIORITY 7u
#define UART_DMA_INT__INTC_NUMBER 50u
#define UART_DMA_INT_INTC_CORTEXM4_ASSIGNED 1
#define UART_DMA_INT_INTC_CORTEXM4_PRIORITY 7u
#define UART_DMA_INT_INTC_NUMBER 50u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* mI2C_SCB_IRQ */
#define mI2C_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define mI2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define mI2C_SCB_IRQ__INTC_NUMBER 44u
#define mI2C_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define mI2C_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define mI2C_SCB_IRQ_INTC_NUMBER 44u

/* ADC_DMA_INT_0 */
#define ADC_DMA_INT_0__INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_0__INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_0__INTC_NUMBER 51u
#define ADC_DMA_INT_0_INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_0_INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_0_INTC_NUMBER 51u

/* ADC_DMA_INT_1 */
#define ADC_DMA_INT_1__INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_1__INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_1__INTC_NUMBER 54u
#define ADC_DMA_INT_1_INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_1_INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_1_INTC_NUMBER 54u

/* ADC_DMA_INT_2 */
#define ADC_DMA_INT_2__INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_2__INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_2__INTC_NUMBER 53u
#define ADC_DMA_INT_2_INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_2_INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_2_INTC_NUMBER 53u

/* ADC_DMA_INT_3 */
#define ADC_DMA_INT_3__INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_3__INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_3__INTC_NUMBER 52u
#define ADC_DMA_INT_3_INTC_CORTEXM4_ASSIGNED 1
#define ADC_DMA_INT_3_INTC_CORTEXM4_PRIORITY 7u
#define ADC_DMA_INT_3_INTC_NUMBER 52u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
